### ISSUE TITLE
Doesn't work for me, dockerhub repo is 404

### ISSUE THREAD

**Issue by sTiKyt** [ravermeister/gitlab#2]
docker: Error response from daemon: pull access denied for hostname, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

'docker login' didn't help

**Comment by sTiKyt** [comment]
Also page at https://hub.docker.com/r/ravermeister/gitlab/ is gone
![image](https://user-images.githubusercontent.com/35602029/152082766-09d29910-fb96-49ed-82e4-ead139c008b7.png)

**Comment by ravermeister** [comment]
could you check again? seems a temporary failure in dockerhub, I could open the page without a login on 02.02.2022 10:00 AM GMT+1

**Comment by sTiKyt** [comment]
Yes, link works now
