### ISSUE TITLE
Container registry disabled

### ISSUE THREAD

**Issue by jaqua** [ravermeister/gitlab#5]
I'm using this docker image on my local server which needs an ARM image. But the container registry seems to be disabled. I'm not sure if it is caused by this image or some misconfiguration on my side.

**Comment by ravermeister** [comment]
I would guess it is a Configuration issue. It's working for me. The exposed registry port is `7050`.  Have you read the doc and configured the external url?
```
################################################################################
## Container Registry settings
##! Docs: https://docs.gitlab.com/ce/administration/container_registry.html
################################################################################

registry_external_url 'https://registry.domain.tld'
```
